[package]
name = "veronica-scene"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
veronica-core.workspace = true
veronica-graph.workspace = true
bevy_ecs.workspace = true
bevy_app.workspace = true
bevy_transform.workspace = true
thiserror.workspace = true
